### ISSUE TITLE
Possible correction for BadUpdates

### ISSUE THREAD

**Issue by amolksagar** [marklcg/jsf-sheet#10]
Hi,

   As per our requirement, we need the jsf sheet to be populated in the tab view only when a certain condition(!listItem.visible) is satisfied.Sample code below:

 <h:panelGrid rendered="#{!listItem.visible}" cellpadding="10" style="height:500px;" width="2000">
	<lcg:sheet id="sheet"  showRowHeaders="false" value="#{listItem.testDataList}" var="test"  label="Sheet" rowKey="#{test.rowIndex}">
	<lcg:column headerText="Industry" readonly="true" colWidth="100" value="#{test.industry}" styleClass="#{test.industrySelection gt 0 ? 'cell-selected' : 'cell-unselected'}"/>
        </lcg:sheet>
  </h:panelGrid>	

When the page loads initially the Sheet widget is hidden and does not even appear in the DOM. Thats as expected. But when the condition mentioned above becomes true and the sheet has to be rendered then a call goes to the method mentioned below in Sheet.java

public void restoreState(FacesContext context, Object state) {}

In this method there is a code snippet

if (restoredBadUpdates == null) {
			**_badUpdates.clear();_**
		} else {
			badUpdates = (List<BadUpdate>) restoredBadUpdates;
		}

The line that I have highlighted above throws a nullpointer exception since the badUpdates object is null. What I did to resolve this issue is that I used a function getBadUpdates() in the same class. This method has a null check and initiates the badUpdates object if it is null

Please let me know whether this would have any issues elsewhere in the code? Also should the restoreState() in Sheet class be called in such cases where it was not loaded in the DOM initially?

**Comment by melloware** [comment]
I just submitted a PR to fix the NPE.  As to your other questions I am not sure.

**Comment by marklcg** [comment]
The restoreState method is required by the UIComponent's StateHolder interface.  It's called during the lifecycle when the view is being restored and, if the rendered indicates it should now be rendered, called for this component.  

I will merge Melloware's changes to fix the NPE and your work around should not be necessary.

**Comment by amolksagar** [comment]
Thanks Mark and Melloware
