### ISSUE TITLE
Jquery Unbind vs Bind in Sheet.js

### ISSUE THREAD

**Issue by melloware** [marklcg/jsf-sheet#2]
In Sheet.js on line 258-260 why do you do an unbind?  According to JQuery docs for unbind what you are doing should not be valid.

http://api.jquery.com/unbind/

Is this supposed to be "bind" and not "unbind"?

**Comment by marklcg** [comment]
I can certainly replace the unbind with off now that it is deprecated, but the intent of that code is to removing the existing "click" event handler, then add our own for sorting. You'll see it removes the "click" then immediately binds a new click event handler using the click() method (think builder pattern).  I will fix to use off.

**Comment by marklcg** [comment]
Fixed in latest snapshot.
