### ISSUE TITLE
Dependency problem

### ISSUE THREAD

**Issue by leolima** [marklcg/jsf-sheet#9]
```
<dependency>
    <groupId>com.lassitercg</groupId>
    <artifactId>jsf-sheet</artifactId>
    <version>1.4</version>
</dependency>
```
this version is not available https://mvnrepository.com/artifact/com.lassitercg

**Comment by marklcg** [comment]
I apologize, I missed logging into Sonatype and releasing the artifact.  It should be syncing now and should be available soon.

**Comment by marklcg** [comment]
Confirmed in maven central.

https://search.maven.org/#artifactdetails%7Ccom.lassitercg%7Cjsf-sheet%7C1.4%7Cjar
